{102301513}-first
west2-online-reserve/collection-python pull request #8
Opened 2023-09-24 11:07 UTC by pplolqq

2023-09-25 08:12 UTC, 1379255913 requested changes

2023-09-25 08:12 UTC, 1379255913 commented on pr_python/python.py
> +        c=input()
建议直接在setData函数中传入需要修改的变量和值，而不是使用input获取

2023-09-25 08:12 UTC, 1379255913 commented on pr_python/python.py
> +    return {"该列表数字个数为：":a}
题目理解有误，指的是比如[1,2,3,4.2]中，2有2个，1，3，4有1个，其他数字为0个这样子

2023-09-25 17:02 UTC, linrongda commented
规范一下文件夹的命名哦

2023-09-26 06:30 UTC, 1379255913 approved these changes, later dismissed

2023-10-01 08:56 UTC, linrongda commented
文件夹命名还是不规范，建议去看看别人怎么命名的，而且不是work4。认真查看文档 https://west2-online.feishu.cn/wiki/Zvqow0CUxig3iWkWQgBcHp4AnHe

2023-10-01 09:32 UTC, linrongda approved these changes
完成的挺好

2023-10-01 09:32 UTC, merged

2023-10-01 09:59 UTC, linrongda commented
python（后端或AI）的考核信息表都没有你，请核实是否在纳新表格中填报Python方向